### ISSUE TITLE
not huge issue, but no level 92

### ISSUE THREAD

**Issue by warlord1352** [c0dycode/Borderlands-Hex-Multitool#22]
so I just updated to 1.27 from my old 1.25 (which I was still able to use and level up to 92. In this new version, however, I am not able to go past 90 even though the comment still says 92 is working.

**Comment by Dyskal** [comment]
to having no problems, level cap with op levels need to be at 100 or lower, in the new dlc the max level is 80 and op level up to OP10 so the level restriction in 1.27 is set to 90 !

**Comment by c0dycode** [comment]
@Dyskal is correct :)

Before the Level increase there always were problems if Character level + OP Levels were above 100.
Since this still seems to be the case, I have adjusted this feature to make up for this :)

Also which comment are you talking about? The one in the readme? I just forgot about adjusting that :)

**Comment by warlord1352** [comment]
oooooh ok i am sorry, I havent gotten to the new DLC yet. i was wondering about that. thank you for quick responses! =)
