### ISSUE TITLE
Hex Multitool freaks out if game has not been launched yet and crashes.

### ISSUE THREAD

**Issue by tyush** [c0dycode/Borderlands-Hex-Multitool#28]
If the game has not been launched yet, the multitool will complain about a missing config and stop responding. It'd be great if a small notice like "Have you launched the game at least once?" or something could pop up and warn the user.

**Comment by tyush** [comment]
Apologies, it says you need to launch the game if you launch the launcher for either BL2 or BLTPS, but the message if you have not ever launched the launcher does not.

**Comment by c0dycode** [comment]
Yeah, the issue is that if any of the previous path's don't exist, that message overwrites the one that it SHOULD display (the one you saw later).

It's noted down, but probably won't make it into THIS version of the tool. I'm currently working on basically the same tool but programmed in C++ instead of C# in order to make it usable on Windows, Linux and Mac.

I'll make sure that this is properly handled in that one though :)
