### ISSUE TITLE
I need help with setting up files

### ISSUE THREAD

**Issue by Iownallnoobs32** [c0dycode/Borderlands-Hex-Multitool#32]
So every time i try to setup files i go to the usual BL2 folder then i go to binaries then win32 and i try to open bl2 (because that's my only option) and it says catastrophic failure

Please help me

**Comment by c0dycode** [comment]
The only "catastrophic failure" I've ever seen is, if you try to open a shortcut, instead of the exe directly.
Double check if that is the case.

**Comment by Iownallnoobs32** [comment]
yeah it is idk where to find the actual exe

**Comment by c0dycode** [comment]
In my case it is in "E:\SteamLibrary\steamapps\common\Borderlands 2\Binaries\Win32"

**Comment by Iownallnoobs32** [comment]
that area doesn't exist on my pc

**Comment by c0dycode** [comment]
Here's how you can find the location:
https://gfycat.com/repulsiveconfusedgilamonster

**Comment by Iownallnoobs32** [comment]
thank you so by any chance can you tell me what i do from there??

sorry if im wasting your time

**Comment by c0dycode** [comment]
No worries, you'll see the address at the top, that's where you navigate to in the FileBrowser Dialog of the Multitool. Make sure you press the correct Button. If you want to setup the BL2 Filepath, you need to click the button that's next to the BL2 Filepath. Otherwise the Filter will only show you the Pre Sequel exe and shortcuts.

**Comment by Iownallnoobs32** [comment]
thank you iv'e successfully setup the path

great thanks to you
