### ISSUE TITLE
The Hex-Edit file is labeled as Malware. Why?

### ISSUE THREAD

**Issue by Ritz144** [c0dycode/Borderlands-Hex-Multitool#38]
is it infected? Safe to download? help

**Comment by c0dycode** [comment]
It's safe to use :)
Here's a VirusTotal scan: https://www.virustotal.com/gui/file/7cd74284c81a476fb4e23a0043ddea36f1dcb5fbd77c64037ab5f2666a9d0db4/detection

I'm not too sure why it suddenly is flagged again by a few AVs. Probably because it now connects to the internet to check for a new version.

You can check it on nexusmods aswell: https://www.nexusmods.com/borderlands2/mods/54/

With 85.000+ total downloads, there would probably be a report by now that there is something fishy going on. :)

**Comment by Ritz144** [comment]
thank you for the help
