### ISSUE TITLE
Borderlands-Hex-Multitool v1.33 contains malware

### ISSUE THREAD

**Issue by CarbonBadger** [c0dycode/Borderlands-Hex-Multitool#39]
Hi @c0dycode ,

thanks for your work on this software. Unfortunately the current version, v1.33, appears to contain malware. BitDefender found the following : "Gen:Variant.Razy.625961" in the .zip file on Github. Could you please look into this.

Cheers.

**Comment by Default-Devv** [comment]
False positives do exist my friend. I've been using this tool for quite
some time, without an antivirus and I've had no issues.

:)

**Comment by c0dycode** [comment]
As @Default-Devv said, that's a false positive.

They probably flag some API's, that allow modification of files, by default.
That's all they'd have done when "scanning" the exe. If they'd check the tool properly (set up filepaths to borderlands exe's) they'd obviously realize there's nothing going on.

AV's randomly flag it, then a few weeks/months later everything is fine again. And at some point the cycle continues. Which is why I also don't really bother with submitting the files to AV's anymore.

The tool has been around since 2017 now and if there'd be anything fishy with it, people most likely would have found out by now.

**Comment by CarbonBadger** [comment]
Thanks for the fast responses guys. I've been using this tool for a while with no problems. Increasing the inventory cap makes it much more playable. I'll ignore the AV warning.

Cheers.

PS. Have made a contribution to @c0dycode  via Nexus Mods.

**Comment by c0dycode** [comment]
Thank you very much ❤️ :)

And you're welcome! Enjoy :)
