### ISSUE TITLE
Level cap

### ISSUE THREAD

**Issue by ImaFiend** [c0dycode/Borderlands-Hex-Multitool#42]
Cant seem to set the level cap. I want to set the max level in the multi tool to 80, but i still gain xp after saving and launching. Everything Else about the multi tool works great and I have no problems with. I have the latest version of the tool (v1.33). What am I missing.

**Comment by c0dycode** [comment]
That usually happened when a user has used an old version of the Multitool before using the newest version of the game, without verifying the game files via steam.

However while checking this, I've encountered a bug aswell.
That bug should be fixed with this version. Let me know if this also fixes your issue. It's possible that you need to fix your exp with "Gibbed" though.

[Multitool 1.34 Test.zip](https://github.com/c0dycode/Borderlands-Hex-Multitool/files/4551613/BL.Hex-Multitool.NET.4.5.zip)

**Comment by ImaFiend** [comment]
I re verified the game files and re hexedited my borderlands 2.exe and now
its working fine. Thanks g, ur the best.

**Comment by c0dycode** [comment]
Glad it's working now :)
Enjoy! 👍
