### ISSUE TITLE
Unable to select filepaths

### ISSUE THREAD

**Issue by AngryCheerio15** [c0dycode/Borderlands-Hex-Multitool#43]
I cant select the Borderlands 2 filepath for the Hex-Multitool. I just downloaded BL2 and the Pre Sequel today from Epic Games and when I choose the file it's listed as an internet shortcut instead of an .exe file. How do I fix this so I can run the Multitool?

**Comment by c0dycode** [comment]
I'm not 100% sure what you mean.

You can click on the button and the dialog pops up fine?
If so, then you just need to navigate to wherever your game is installed to.

The exe that you need is at "E:\Borderlands2\Binaries\Win32".

Also make sure that if you click on the BL2-Button, you can only select/see the BL2 exe.
For TPS it's the same.

Otherwise feel free to post a screenshot of the issue 👍

**Comment by AngryCheerio15** [comment]
![BL2 file screenshot](https://user-images.githubusercontent.com/66139112/83299938-19b2d100-a1c5-11ea-826d-c3bf2672cc85.png)

**Comment by c0dycode** [comment]
That's the folder in the Documents.
That's not the correct folder.

I'm not too familiar with EGS, so I can't tell you if it shows you the installocation somewhere, besides when starting the download.

You could try something like "C:\Program Files(x86)\Epic Games Store\" or something like that.

You could also open the game, the TaskManager and then rightclick the Borderlands process and select "Open file location". That should show you the path.

**Comment by c0dycode** [comment]
Make sure that the game is closed though, if you try to use the Multitool! 👍

**Comment by AngryCheerio15** [comment]
I found it the correct file, thanks for the help!

**Comment by MIDO9080** [comment]
> I found it the correct file, thanks for the help!

what is the file i cant find it

**Comment by c0dycode** [comment]
It's an exe file.

If you're in the correct folder, it should be the only file you see.
