### ISSUE TITLE
"object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by Shrillex** [c0dycode/Borderlands-Hex-Multitool#45]
I have set the file path correctly but when i check the boxes to disable the sanity checks it says "object reference not set to an instance of an object" please help I have deleted the game, deleted hex and re-downloaded both multiple times but it doesn't work? The message appears after i click apply then closes hex and undoes the checks.
also Im on the epic games version.

**Comment by c0dycode** [comment]
In 95% of the cases where it shows an error, it's due to something like an antivirus interfering/blocking.

Disable that temporarily and try again.
If that doesn't help, try rebooting your PC or try again a few more times.

Some people had similar issues and they just kept trying and eventually it worked.

**Comment by Shrillex** [comment]
I have tried both reboot and turning off antivirus neither have worked for me can you go into a little more detail of the antivirus cause i may have done that wrong

**Comment by c0dycode** [comment]
Unfortunately no, as I'm not familiar with every antivirus software out there.

You should be able to find out how to do it properly by using a search engine of your choice and just search for "disable <your antivirus software>".
