### ISSUE TITLE
Issue During SetConosleKey

### ISSUE THREAD

**Issue by GraySanSama** [c0dycode/Borderlands-Hex-Multitool#48]
I'm having an issue when attempting to apply the patch to the Pre-Sequel, namely when trying to set the console key. The error message says "could not find a part of the path." The .exe is located in the correct place and the process went just fine for Borderlands 2. I've tried moving the application around and redownloading the program several times. I have absolutely no programming experience or background so forgive me if I'm missing something super obvious.

**Comment by c0dycode** [comment]
You need to launch TPS so that the "ini" file is created.
The file that's missing is "Documents\my games\Borderlands The Pre-Sequel\WillowGame\Config\WillowInput.ini".

If that's not there, the tool cannot edit it to adjust the ConsoleKey.
Sometimes it's necessary to change some settings or play the game for a couple minutes for that file to be created.

**Comment by GraySanSama** [comment]
I did try this before the last reinstall, though i haven’t tried it since I’ll give that a go.
