### ISSUE TITLE
KeyLogger

### ISSUE THREAD

**Issue by Zairen** [c0dycode/Borderlands-Hex-Multitool#53]
I downloaded the Master file and windows found a keylogger (something else as well cant remember) but when I download the .Net 4.5 file I dont get a windows defender alert, this is very concerning.

**Comment by c0dycode** [comment]
If you download the whole repo (master file) then that's a different zip-file and probably it's therefore being flagged.
Effectively the zip-file inside of that one is the same exact one as if you'd directly download just the zip-file.

You can use something like 7Zip to compare the hashes and they'd be the same.

I've only submitted the `BL Hex-Multitool .NET 4.5.zip`-file to Microsoft, not the repo-zip. That's why one is "whitelisted" and the other one is not.
